import { $TSFIXME } from "../ts-fix-me";

/**
 * This is the subreddit after fetching.
 * @example
 * new Subreddit({ displayName: 'all' }, snoowrap, false).fetch();
 */
export interface FetchedSubreddit {
    displayName: string;
};

// {
//     "user_flair_background_color": null,
//     "submit_text_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;hr/&gt;\n\n&lt;p&gt;&lt;strong&gt;1.&lt;/strong&gt; A subreddit will only be accepted if it passes the following conditions:&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;a)&lt;/strong&gt; The subreddit can be no newer than 14 days. &lt;/p&gt;\n\n&lt;p&gt;&lt;em&gt;This allows the moderators here to be certain the subreddit is steadily being posted to and actively moderated.&lt;/em&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;b)&lt;/strong&gt; If you moderate the aforementioned subreddit, you may only advertise it &lt;strong&gt;once per month.&lt;/strong&gt; You may, however, create a self post relating to it if you need help. &lt;/p&gt;\n\n&lt;p&gt;&lt;em&gt;To clarify, advertising is linking to your subreddit and/or encouraging people to go to it.&lt;/em&gt;&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;p&gt;&lt;strong&gt;2.&lt;/strong&gt; You may also create a self post if you are looking for a specific subreddit or need help.&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;p&gt;&lt;strong&gt;3.&lt;/strong&gt; Do not link to anything outside of reddit in a submission title, and only in a comment if it is relevant.&lt;/p&gt;\n\n&lt;hr/&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
//     "restrict_posting": true,
//     "user_is_banned": false,
//     "free_form_reports": true,
//     "wiki_enabled": true,
//     "user_is_muted": false,
//     "user_can_flair_in_sr": null,
//     "display_name": "subreddit",
//     "header_img": null,
//     "title": "/r/subreddit: Share a subreddit!",
//     "allow_galleries": true,
//     "icon_size": null,
//     "primary_color": "",
//     "active_user_count": 21,
//     "icon_img": "",
//     "display_name_prefixed": "r/subreddit",
//     "accounts_active": 21,
//     "public_traffic": false,
//     "subscribers": 16156,
//     "user_flair_richtext": [],
//     "name": "t5_2qi8c",
//     "quarantine": false,
//     "hide_ads": false,
//     "prediction_leaderboard_entry_type": "IN_FEED",
//     "emojis_enabled": false,
//     "advertiser_category": "",
//     "public_description": "/r/subreddit \n\n---\nCome here to share an unrecognized subreddit or to find a subreddit you've been looking for!\n___",
//     "comment_score_hide_mins": 0,
//     "allow_predictions": false,
//     "user_has_favorited": false,
//     "user_flair_template_id": null,
//     "community_icon": "",
//     "banner_background_image": "",
//     "original_content_tag_enabled": false,
//     "community_reviewed": true,
//     "submit_text": "---\n**1.** A subreddit will only be accepted if it passes the following conditions:\n\n**a)** The subreddit can be no newer than 14 days. \n\n*This allows the moderators here to be certain the subreddit is steadily being posted to and actively moderated.*\n\n**b)** If you moderate the aforementioned subreddit, you may only advertise it **once per month.** You may, however, create a self post relating to it if you need help. \n\n*To clarify, advertising is linking to your subreddit and/or encouraging people to go to it.*\n\n---\n**2.** You may also create a self post if you are looking for a specific subreddit or need help.\n\n---\n**3.** Do not link to anything outside of reddit in a submission title, and only in a comment if it is relevant.\n\n---",
//     "description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;hr/&gt;\n\n&lt;p&gt;&lt;a href=\"http://www.reddit.com/r/subreddit/wiki/faq\"&gt;Please read our FAQ.&lt;/a&gt;&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;hr/&gt;\n\n&lt;h1&gt;Submission Guidelines:&lt;/h1&gt;\n\n&lt;p&gt;&lt;strong&gt;1.&lt;/strong&gt; A subreddit will only be accepted if it passes the following conditions:&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;a)&lt;/strong&gt; The subreddit &lt;strong&gt;can not be newer than 14 days.&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;em&gt;Unless it is very clearly active, this allows the moderators here to be certain the subreddit is going to be steadily posted to and actively moderated.&lt;/em&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;b)&lt;/strong&gt; If you moderate the aforementioned subreddit, you may only advertise it &lt;strong&gt;once per month.&lt;/strong&gt; You may, however, create a self post relating to it if you need help. &lt;/p&gt;\n\n&lt;p&gt;&lt;em&gt;To clarify, advertising is linking to your subreddit and/or encouraging people to go to it.&lt;/em&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;c)&lt;/strong&gt; The subreddit must be active, this means having been posted to &lt;strong&gt;once within the last week&lt;/strong&gt; or &lt;strong&gt;twice within the last month.&lt;/strong&gt;\nActive is also defined by the moderators&amp;#39; activity, we should see something &lt;strong&gt;recently posted by a moderator&lt;/strong&gt; and &lt;strong&gt;not see any spam.&lt;/strong&gt;&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;p&gt;&lt;strong&gt;2.&lt;/strong&gt; You may also create a self post if you are looking for a specific subreddit or need help.&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;p&gt;&lt;strong&gt;3.&lt;/strong&gt; Do not link to anything outside of reddit in a submission title, and only in a comment if it is relevant.&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;hr/&gt;\n\n&lt;p&gt;&lt;a href=\"http://www.reddit.com/r/subreddit/wiki/faq\"&gt;Please read our FAQ.&lt;/a&gt;&lt;/p&gt;\n\n&lt;h4&gt;&lt;strong&gt;Please remember that any subreddit posted here must be at least 14 days old.&lt;/strong&gt;&lt;/h4&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
//     "spoilers_enabled": true,
//     "header_title": "Mud! Kip! Mud! Kip!",
//     "header_size": null,
//     "user_flair_position": "left",
//     "all_original_content": false,
//     "has_menu_widget": false,
//     "is_enrolled_in_new_modmail": null,
//     "key_color": "#ff8717",
//     "can_assign_user_flair": false,
//     "created": 1211980374,
//     "wls": 6,
//     "show_media_preview": true,
//     "submission_type": "any",
//     "user_is_subscriber": false,
//     "disable_contributor_requests": false,
//     "allow_videogifs": true,
//     "user_flair_type": "text",
//     "allow_polls": true,
//     "collapse_deleted_comments": false,
//     "emojis_custom_size": null,
//     "public_description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;&lt;a href=\"/r/subreddit\"&gt;/r/subreddit&lt;/a&gt; &lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;p&gt;Come here to share an unrecognized subreddit or to find a subreddit you&amp;#39;ve been looking for!&lt;/p&gt;\n\n&lt;hr/&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
//     "allow_videos": false,
//     "is_crosspostable_subreddit": true,
//     "notification_level": null,
//     "can_assign_link_flair": true,
//     "accounts_active_is_fuzzed": false,
//     "submit_text_label": "Submit a new self post",
//     "link_flair_position": "left",
//     "user_sr_flair_enabled": true,
//     "user_flair_enabled_in_sr": false,
//     "allow_chat_post_creation": false,
//     "allow_discovery": true,
//     "user_sr_theme_enabled": true,
//     "link_flair_enabled": true,
//     "subreddit_type": "public",
//     "suggested_comment_sort": null,
//     "banner_img": "",
//     "user_flair_text": null,
//     "banner_background_color": "",
//     "show_media": true,
//     "id": "2qi8c",
//     "user_is_moderator": false,
//     "over18": false,
//     "description": "---\n[Please read our FAQ.](http://www.reddit.com/r/subreddit/wiki/faq)\n\n---\n---\n#Submission Guidelines:\n\n**1.** A subreddit will only be accepted if it passes the following conditions:\n\n**a)** The subreddit **can not be newer than 14 days.**\n\n*Unless it is very clearly active, this allows the moderators here to be certain the subreddit is going to be steadily posted to and actively moderated.*\n\n**b)** If you moderate the aforementioned subreddit, you may only advertise it **once per month.** You may, however, create a self post relating to it if you need help. \n\n*To clarify, advertising is linking to your subreddit and/or encouraging people to go to it.*\n\n**c)** The subreddit must be active, this means having been posted to **once within the last week** or **twice within the last month.**\nActive is also defined by the moderators' activity, we should see something **recently posted by a moderator** and **not see any spam.**\n\n---\n**2.** You may also create a self post if you are looking for a specific subreddit or need help.\n\n---\n**3.** Do not link to anything outside of reddit in a submission title, and only in a comment if it is relevant.\n\n---\n---\n[Please read our FAQ.](http://www.reddit.com/r/subreddit/wiki/faq)\n\n\n\n####**Please remember that any subreddit posted here must be at least 14 days old.**",
//     "is_chat_post_feature_enabled": true,
//     "submit_link_label": "Submit a new subreddit",
//     "user_flair_text_color": null,
//     "restrict_commenting": false,
//     "user_flair_css_class": null,
//     "allow_images": true,
//     "lang": "en",
//     "whitelist_status": "all_ads",
//     "url": "/r/subreddit/",
//     "created_utc": 1211980374,
//     "banner_size": null,
//     "mobile_banner_image": "",
//     "user_is_contributor": false,
//     "allow_predictions_tournament": false
//   }